name: Instrumented Tests

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: UI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Run Instrumented Tests
        uses: emulator-wtf/run-tests@v0.9.9
        with:
          api-token: ${{ secrets.EW_API_TOKEN }}
          app: app/build/outputs/apk/debug/app-debug.apk
          test: app/build/outputs/apk/androidTest/app-debug-androidTest.apk
          outputs-dir: build/test-results
      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the tests fail
        with:
          report_paths: 'build/test-results/**/*.xml'
